### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by kenahoo-windlogics**
I added bunch of regression tests.  There are a few that aren't currently passing, I left them commented out so the tests would succeed overall.  (I couldn't find a "TODO" test mechanism in `testthat` so I opened [a feature request](https://github.com/hadley/testthat/issues/234) for it.)

### CODE REVIEW

**Comment by kenahoo-windlogics** [comment]
I also have a "FixBugs" branch that picks up where this one leaves off, fixing the problems I found in the tests:

    https://github.com/kenahoo-windlogics/pack/compare/AddTests...kenahoo-windlogics:FixBugs

If you approve this PR I can rebase my FixBugs branch on top of it for a cleaner merge.

**Comment by joshuaulrich** [comment]
Thanks! How did you create the raw vectors you're testing against?

Regarding your "FixBugs" branch: can you please provide more details in the commit message about what is being fixed? I try to follow [these suggestions](https://wiki.openstack.org/wiki/GitCommitMessages#Information_in_commit_messages), paying special attention to explaining the problem and the solution.

**Comment by kenahoo** [comment]
To find the appropriate raw vectors, sometimes I used Perl (in those cases I pasted the Perl code as comments into the tests), sometimes just mental conversion between decimal & hex, I guess.  I can try to make them more explicit.

**Comment by joshuaulrich** [comment]
This has been merged into the develop branch. Note that I made a few changes and squashed all the commits into a single commit.

**Comment by kenahoo-windlogics** [comment]
Good point about the native format.  Looks like we can check `.Platform$endian` to be aware of the machine type.

**Pull request closed without merging**
